### ISSUE TITLE
error decrypting and support for .ini files

### ISSUE THREAD

**Issue by xillwillx** [HyperSine/how-does-MobaXterm-encrypt-password#2]
playing around with the python scipt , I got ShowMobaXterm.py to properly dump from the registry automatically. 
```
[*] Name:     ssh22:root@192.168.43.11
[*] Password: toor

```
couldnt get MobaXtermCipher.py to manually decrypt the password from registry using the proper parameters needed, i.e.  session/computername/username/host/user/hash but get error 

```
MobaXtermCipher.py dec -sp 264976199786264976199786 -sysh TestComputer  -sysu TestUser -h 192.168.43.1 -u root jl917Wf+/cwNBCEgG2lRPu

_File "C:\dev\code\MobaXtermCipher.py", line 330, in <module>
    exit(Main(len(sys.argv), sys.argv))
  File "C:\dev\code\MobaXtermCipher.py", line 323, in Main
    raise ValueError('Ambiguous parameters are detected.')
ValueError: Ambiguous parameters are detected_
```
 ```
MobaXtermCipher.py dec -sysh ShadowSurface -sysu DoubleSine -sp 165821882556840 -h 45.32.110.171 -u root F0+wuBvbe9qPW6ypiOeYHTHhKdShRc/nXaM1Ky1jeTfw46TzQoSesX9buGm0WW36yP4lhH70ZCHZpEo4wLJhIl1
Traceback (most recent call last):
  File "C:\dev\code\MobaXtermCipher.py", line 330, in <module>
    exit(Main(len(sys.argv), sys.argv))
  File "C:\dev\code\MobaXtermCipher.py", line 323, in Main
    raise ValueError('Ambiguous parameters are detected.')
ValueError: Ambiguous parameters are detected.
```

also is it possible to support mobaxterm.ini files along with registry

**Comment by xillwillx** [comment]
ended up playing with your code and getting it to work 
https://github.com/xillwillx/MobaXterm-Decryptor
