### ISSUE TITLE
LookupError: unknown encoding: ansi

### ISSUE THREAD

**Issue by mobidyc** [HyperSine/how-does-MobaXterm-encrypt-password#4]
For what I see, there is not "ansi" encoding in python3 (or at least in recent version).

Replacing "ansi" with "utf-8" solves the situation

https://stackoverflow.com/questions/22279413/python-convert-encodinglookuperror-unknown-encoding-ansi

`Traceback (most recent call last):
  File "MobaXtermCipher.py", line 330, in <module>
    exit(Main(len(sys.argv), sys.argv))
  File "MobaXtermCipher.py", line 270, in Main
    cipher = MobaXtermCrypto(sys_hostname.encode('ansi'), sys_username.encode('ansi'))
LookupError: unknown encoding: ansi
`

**Comment by the-Arioch** [comment]
Correct for Windows should be "mbcs" encoding

See https://github.com/xillwillx/MobaXterm-Decryptor/pull/2

...but yeah, INI files no more decoded
